import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  approvedImageList: [],
  rejectedImageList: [],
};

const imagesSlice = createSlice({
  name: 'images',
  // The intial state value we pass for the reducers. A state the first time it gets called.
  initialState,
  reducers: {
    imageApproved(state, action) {
      const randomImageObject = action.payload;
      const randomImageId = randomImageObject.id;
      const approvedImageListIds = state.approvedImageList.map(
        (image) => image.id
      );

      if (!approvedImageListIds.includes(randomImageId)) {
        state.approvedImageList.push(randomImageObject);
      }
    },

    imageRejected(state, action) {
      const randomImageObject = action.payload;
      state.rejectedImageList.push(randomImageObject);
    },
  },
});

/** actions creators (generated by createSlice) with the same name as the reducer functions  */
export const { imageApproved, imageRejected } = imagesSlice.actions;

/** 2) Exporting a reducer function for the images logic.
 * We import this reducer function in the store.
 */
export default imagesSlice.reducer;

/** A slice is a collection of Redux reducer logic
 * and actions for a single feature in our app.
 *
 * A function createSlice takes care of the work of generating
 * action type strings, action creator functions, and action objects
 *
 * What do we actually have under the hood:
 *  an action type of {type: "images/imageApproved"}
 *  an action type of {type: "images/imageRejected"}
 *  an action type of {type: "images/buttonClicked"}
 *
 *
 * Now we have three  reducer functions that corresponds to the three different action types
 * that were dispatched by clicking the different btns.
 * */
